version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: docker-symfony-nginx
        ports:
            - '8088:80'
        volumes:
            - ./symfony/:/var/www/app
            - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
        networks:
            - symfony
    php:
        build:
            context: ./docker/php
        container_name: docker-symfony-php
        environment:
            APP_ENV: dev
        volumes:
            - ./symfony/:/var/www/app
        ports:
            - '9003:9000'
        networks:
            - symfony
networks:
    symfony:
